### ISSUE TITLE
Sometimes the json with data is not loaded on first click of opening the extension

### ISSUE THREAD

**Issue by lukaskoeller** [JSHSJ/test-account-manager#6]
## To reproduce
* Sometimes (Unfortunately, I can't see here rule her…) when you click on the extension icon to open it
* It shows that there are no accounts
* You click the icon again to close it
* You click it again to open it
* Tada, all accounts are there

**Comment by lukaskoeller** [comment]
<img width="836" alt="Screenshot 2023-02-11 at 11 58 43" src="https://user-images.githubusercontent.com/10390627/218254475-817f4467-7f22-419d-83b8-93f594a6f907.png">
 Here happened again upon opening

**Comment by JSHSJ** [comment]
I think this should be fixed
