### ISSUE TITLE
feat: Would be nice to see at the top or bottom how many accounts are currently in the view

### ISSUE THREAD

**Issue by lukaskoeller** [JSHSJ/test-account-manager#7]
E.g. you scroll down and the last line says:

```
1337 test accounts
```

or

```
Total accounts of 1337
```
or something similar

**Comment by JSHSJ** [comment]
You *could* do this, but it would also be visual clutter imo. It's not crucial to the main usecase.

**Comment by JSHSJ** [comment]
We did it!
